feat: add muusik.app
Androz2091/discord-player pull request #1887
Opened 2024-01-18 18:25 UTC by JayXTQ

## Changes
added my bot [muusik.app](https://muusik.app)

## Status

- [x] These changes have been tested and formatted properly.
- [x] This PR includes only documentation changes, no code change.
- [ ] This PR introduces some Breaking changes.

2024-01-18 19:09 UTC, twlite requested changes

2024-01-18 19:09 UTC, twlite commented on apps/website/src/data/showcase.ts
> +                version: 'v1.2.1',
hi, this is supposed to represent discord-player version.

2024-01-18 22:28 UTC, JayXTQ commented
fixed, didn't know :3

2024-01-19 15:11 UTC, twlite approved these changes

2024-01-19 15:11 UTC, merged