Add warning to youtube extractor
Androz2091/discord-player pull request #1923
Opened 2024-07-19 10:33 UTC by retrouser955

## Changes
Adds a warning to YouTube extractor via `process.emitWarning()`, warning the user of some instability nature of Youtube Extractor and recommending discord-player-youtubei

## Status

- [x] These changes have been tested and formatted properly.
- [ ] This PR includes only documentation changes, no code change.
- [ ] This PR introduces some Breaking changes.

2024-07-19 10:36 UTC, twlite reviewed
we should probably document this as well, and is this extractor listed in showcase?

2024-07-19 10:38 UTC, retrouser955 commented
Yes definitely. One slight problem. I have no idea how to modify the documentation. I'll try to tweak some settings and hope it works.

2024-07-19 11:50 UTC, twlite requested changes

2024-07-19 11:50 UTC, twlite commented on README.md
> +*The default Youtube streaming appears to be unstable due to recent changes. It is recommend to install [`discord-player-youtubei`](https://npm.im/discord-player-youtubei)*
```suggestion
* The default Youtube streaming appears to be unstable due to recent changes. It is recommend to install [`discord-player-youtubei`](https://npm.im/discord-player-youtubei)*
```

2024-07-19 11:50 UTC, twlite commented on apps/website/src/data/showcase.ts
> +            description: "Super charging your bot. dpy is a tiny extractor module to test the validity of youtubei.js in discord-player version 7.",
Maybe make it more informative such that people understand this is better than default youtube extractor.

2024-07-19 11:50 UTC, twlite commented on apps/website/src/pages/guide/_guides/welcome/welcome.mdx
> +*The default Youtube streaming appears to be unstable due to recent changes. It is recommend to install [`discord-player-youtubei`](https://npm.im/discord-player-youtubei)*
```suggestion
* The default Youtube streaming appears to be unstable due to recent changes. It is recommend to install [`discord-player-youtubei`](https://npm.im/discord-player-youtubei)*
```

2024-07-19 11:50 UTC, twlite commented on packages/extractor/src/extractors/YoutubeExtractor.ts
> +        process.emitWarning("YoutubeExtractor uses scraping-based streaming libraries which is known to be unstable at times.\nAn alternative is to use discord-player-youtubei https://github.com/retr
```suggestion
        process.emitWarning("YoutubeExtractor uses scraping-based streaming libraries which is known to be unstable at times. An alternative is to use discord-player-youtubei https://github.com/retrouser955/discord-player-youtubei");
```

Could we also link the github issue here?

2024-07-20 06:14 UTC, twlite approved these changes

2024-07-20 06:14 UTC, merged