add missing types & docs
Androz2091/discord-player pull request #308
Opened 2021-02-27 11:20 UTC by Dev-CasperTheGhost

## This PR includes

- Added missing documentation for few Queue getters
- Added missing TypeScript types for `Queue#totalTime` and `PlayerError`

closes #305

2021-02-27 22:29 UTC, Androz2091 requested changes
Thank you 👍 
here are some changes, built in types are lowercase in all the rest of the code

2021-02-27 22:29 UTC, Androz2091 commented on src/Queue.js
> +     * @type {Number}
```suggestion
     * @type {number}
```

2021-02-27 22:29 UTC, Androz2091 commented on src/Queue.js
> +     * @type {Number}
```suggestion
     * @type {number}
```

2021-02-27 22:29 UTC, Androz2091 commented on src/Queue.js
> +     * @type {Number}
```suggestion
     * @type {number}
```

2021-02-28 06:09 UTC, Dev-CasperTheGhost commented
Updated the types to lowercase :)

2021-02-28 07:20 UTC, Androz2091 approved these changes
Thank you 👍

2021-02-28 07:20 UTC, merged